// generated by supabase gen types typescript
//
// Stub. The real types are produced by running:
//   supabase gen types typescript --project-id <ref> > src/lib/supabase/database.types.ts
// after the Supabase project is provisioned and migrations are applied.
//
// Until then, the typed Supabase clients in client.ts and server.ts fall
// back to `any` for the Database generic. Application code that depends
// on table shapes is added in later PRs (PR 4 applications, PR 3 contacts,
// etc.) and will pick up the real types when this file is replaced.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}