// generated by supabase gen types typescript
//
// Stub. The real types are produced by running:
//   supabase gen types typescript --project-id <ref> > src/lib/supabase/database.types.ts
// after the Supabase project is provisioned and migrations are applied.
//
// Until then, the typed Supabase clients in client.ts and server.ts pick up
// per-table shapes incrementally. Application code that depends on table
// shapes adds its table here when it lands (see PR 2 adding `platforms`).
// PR 6 will replace this file with the output of `supabase gen types`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Shape of one row from the `platforms` table.
 *
 * Source of truth: supabase/migrations/001_initial_schema.sql
 *   id          uuid primary key default gen_random_uuid()
 *   user_id     uuid references auth.users(id) on delete cascade -- null for seeds
 *   name        text not null
 *   hostname    text not null
 *   is_custom   boolean not null default false
 *   created_at  timestamptz not null default now()
 */
type PlatformRow = {
  id: string;
  user_id: string | null;
  name: string;
  hostname: string;
  is_custom: boolean;
  created_at: string;
};

type PlatformInsert = {
  id?: string;
  user_id?: string | null;
  name: string;
  hostname: string;
  is_custom?: boolean;
  created_at?: string;
};

type PlatformUpdate = Partial<PlatformInsert>;

export interface Database {
  public: {
    Tables: {
      contacts: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          linkedin_url: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          linkedin_url?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["contacts"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "contacts_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      resumes: {
        Row: {
          id: string;
          user_id: string;
          label: string;
          file_path: string;
          file_hash: string;
          file_size: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          label: string;
          file_path: string;
          file_hash: string;
          file_size: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["resumes"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "resumes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      platforms: {
        Row: PlatformRow;
        Insert: PlatformInsert;
        Update: PlatformUpdate;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
